### ISSUE TITLE
AnnotationFilter not extending Versioned?

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/AnnotationFilter#3]
I was just wondering, `AnnotationFilter` is not extending the `Versioned` class from `Biobase`. I thought all S4classes in Bioconductor *should* extend this class. I'm also happy if it doesn't keeping the class *light weighted*.
Actually I've seen some performance issues in `MSnbase`'s `Spectrum` classes related to that. `Spectrum` does extend `Versioned` and each time a new `Spectrum` is created the `validObject` from `Spectrum`, `Versioned` and all other super classes is called. That has a pretty bad influence on the performance when a file is imported and several thousand `Spectrum` classes are generated.

**Comment by mtmorgan** [comment]
Even though I wrote the class, I think Versioned isn't really useful in practice and don't want to introduce the dependency.

Off topic, but the 'several thousand `Spectrum` classes' problem might be a conceptual problem with the implementation -- it is perhaps better to think of Spectrum as a collection of Spectrum (like `character()` can be length 0, 1, ...), and there something like in the Compressed*List classes of S4Vectors, where there's a 'partitioning' that serves to group the vector components defining individual classes. Some operations are very fast, and one creates a single object rather than thousands. It would run into problems if the total length of the object gets longer than R's `.Machine$integer.max`. I wouldn't suggest this change for existing code, but going forward...

**Comment by jorainer** [comment]
Fine for me.

And thanks for the suggestion on `Spectrum` - that's something we might consider.
